"""Sample portfolio fixtures for tests and local experimentation."""

from __future__ import annotations

from datetime import date

from ai_pm_agent.portfolio.models import Holding, LookThroughComponent, PortfolioSnapshot


def build_sample_portfolio_snapshot() -> PortfolioSnapshot:
    """Build a deterministic sample portfolio.

    Values here are fake test data only. They are not live prices, trade
    recommendations, or a representation of an actual account.
    """

    return PortfolioSnapshot(
        as_of_date=date(2026, 6, 6),
        base_currency="USD",
        cash=12_500.0,
        cash_currency="USD",
        benchmark="QQQ",
        notes="Fixture values are fake test data only.",
        holdings=[
            Holding(
                ticker="TQQQ",
                name="ProShares UltraPro QQQ",
                market="NASDAQ",
                quantity=140.0,
                cost_basis=58.0,
                current_price=72.0,
                asset_class="leveraged_etf",
                instrument_type="leveraged_etf",
                issuer_name="ProShares",
                issuer_canonical_id="PROSHARES",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Diversified",
                industry="Leveraged ETF",
                theme=["leveraged ETF", "mega-cap tech"],
                risk_bucket="leveraged_etf",
                base_currency="USD",
                lookthrough_source="Manual fixture weights, not provider data.",
                lookthrough_components=[
                    LookThroughComponent(
                        component_issuer_name="Microsoft",
                        component_issuer_canonical_id="MICROSOFT",
                        component_ticker="MSFT",
                        component_weight=0.08,
                        sector="Information Technology",
                        industry="Software",
                        country_of_risk="United States",
                        region="North America",
                        theme=["cloud AI", "mega-cap tech", "AI infrastructure"],
                        source_note="Manual fixture component.",
                    ),
                    LookThroughComponent(
                        component_issuer_name="NVIDIA",
                        component_issuer_canonical_id="NVIDIA",
                        component_ticker="NVDA",
                        component_weight=0.07,
                        sector="Information Technology",
                        industry="Semiconductors",
                        country_of_risk="United States",
                        region="North America",
                        theme=["AI infrastructure", "semiconductor"],
                        source_note="Manual fixture component.",
                    ),
                    LookThroughComponent(
                        component_issuer_name="Nasdaq 100 residual",
                        component_issuer_canonical_id="NASDAQ_100_RESIDUAL",
                        component_weight=0.85,
                        sector="Diversified",
                        industry="Index residual",
                        country_of_risk="United States",
                        region="North America",
                        theme=["mega-cap tech"],
                        source_note="Manual fixture residual.",
                    ),
                ],
                notes="3x Nasdaq exposure fixture.",
            ),
            Holding(
                ticker="SOXL",
                name="Direxion Daily Semiconductor Bull 3X Shares",
                market="NYSEARCA",
                quantity=180.0,
                cost_basis=35.0,
                current_price=44.0,
                asset_class="leveraged_etf",
                instrument_type="leveraged_etf",
                issuer_name="Direxion",
                issuer_canonical_id="DIREXION",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Information Technology",
                industry="Leveraged semiconductor ETF",
                theme=["leveraged ETF", "semiconductor", "AI infrastructure"],
                risk_bucket="leveraged_etf",
                base_currency="USD",
                lookthrough_source="Manual fixture weights, not provider data.",
                lookthrough_components=[
                    LookThroughComponent(
                        component_issuer_name="NVIDIA",
                        component_issuer_canonical_id="NVIDIA",
                        component_ticker="NVDA",
                        component_weight=0.12,
                        sector="Information Technology",
                        industry="Semiconductors",
                        country_of_risk="United States",
                        region="North America",
                        theme=["AI infrastructure", "semiconductor"],
                        source_note="Manual fixture component.",
                    ),
                    LookThroughComponent(
                        component_issuer_name="Semiconductor basket residual",
                        component_issuer_canonical_id="SEMICONDUCTOR_BASKET_RESIDUAL",
                        component_weight=0.88,
                        sector="Information Technology",
                        industry="Semiconductors",
                        country_of_risk="Global",
                        region="Global",
                        theme=["semiconductor", "AI infrastructure"],
                        source_note="Manual fixture residual.",
                    ),
                ],
                notes="3x semiconductor exposure fixture.",
            ),
            Holding(
                ticker="NVDA",
                name="NVIDIA",
                market="NASDAQ",
                quantity=70.0,
                cost_basis=105.0,
                current_price=130.0,
                asset_class="equity",
                instrument_type="stock",
                issuer_name="NVIDIA",
                issuer_canonical_id="NVIDIA",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Information Technology",
                industry="Semiconductors",
                theme=["AI infrastructure", "semiconductor"],
                risk_bucket="single_name_growth",
                base_currency="USD",
            ),
            Holding(
                ticker="7709.HK",
                name="SK Hynix proxy / HY9H / 7709.HK",
                market="HKEX",
                currency="HKD",
                quantity=500.0,
                cost_basis=80.0,
                current_price=92.0,
                asset_class="equity",
                instrument_type="stock",
                issuer_name="SK Hynix",
                issuer_canonical_id="SK_HYNIX",
                underlying_issuer_name="SK Hynix",
                underlying_ticker="000660.KS",
                listing_country="Hong Kong",
                country_of_risk="South Korea",
                region="Asia",
                sector="Information Technology",
                industry="Semiconductors",
                theme=["HBM", "semiconductor", "AI infrastructure"],
                risk_bucket="semiconductor_cycle",
                trading_currency="HKD",
                base_currency="USD",
                fx_rate_to_base=0.128,
            ),
            Holding(
                ticker="HY9H",
                name="SK Hynix GDS-like holding",
                market="FWB",
                currency="EUR",
                quantity=40.0,
                cost_basis=150.0,
                current_price=160.0,
                asset_class="gds",
                instrument_type="gds",
                issuer_name="SK Hynix",
                issuer_canonical_id="SK_HYNIX",
                underlying_issuer_name="SK Hynix",
                underlying_ticker="000660.KS",
                listing_country="Germany",
                country_of_risk="South Korea",
                region="Asia",
                sector="Information Technology",
                industry="Semiconductors",
                theme=["HBM", "semiconductor", "AI infrastructure"],
                risk_bucket="semiconductor_cycle",
                trading_currency="EUR",
                base_currency="USD",
                fx_rate_to_base=1.08,
                notes="Fake GDS-like fixture for issuer-normalization tests.",
            ),
            Holding(
                ticker="MU",
                name="Micron Technology",
                market="NASDAQ",
                quantity=55.0,
                cost_basis=98.0,
                current_price=118.0,
                asset_class="equity",
                instrument_type="stock",
                issuer_name="Micron Technology",
                issuer_canonical_id="MICRON",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Information Technology",
                industry="Semiconductors",
                theme=["HBM", "semiconductor"],
                risk_bucket="semiconductor_cycle",
                base_currency="USD",
            ),
            Holding(
                ticker="GOOGL",
                name="Alphabet",
                market="NASDAQ",
                quantity=35.0,
                cost_basis=160.0,
                current_price=185.0,
                asset_class="equity",
                instrument_type="stock",
                issuer_name="Alphabet",
                issuer_canonical_id="ALPHABET",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Communication Services",
                industry="Internet Content and Information",
                theme=["cloud AI", "mega-cap tech"],
                risk_bucket="mega_cap_quality",
                base_currency="USD",
            ),
            Holding(
                ticker="MSFT",
                name="Microsoft",
                market="NASDAQ",
                quantity=22.0,
                cost_basis=405.0,
                current_price=470.0,
                asset_class="equity",
                instrument_type="stock",
                issuer_name="Microsoft",
                issuer_canonical_id="MICROSOFT",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Information Technology",
                industry="Software",
                theme=["cloud AI", "mega-cap tech", "AI infrastructure"],
                risk_bucket="mega_cap_quality",
                base_currency="USD",
            ),
            Holding(
                ticker="TSLA",
                name="Tesla",
                market="NASDAQ",
                quantity=28.0,
                cost_basis=210.0,
                current_price=245.0,
                asset_class="equity",
                instrument_type="stock",
                issuer_name="Tesla",
                issuer_canonical_id="TESLA",
                listing_country="United States",
                country_of_risk="United States",
                region="North America",
                sector="Consumer Discretionary",
                industry="Auto Manufacturers",
                theme=["EV / autonomy", "mega-cap tech"],
                risk_bucket="high_beta",
                base_currency="USD",
            ),
            Holding(
                ticker="ETHA",
                name="iShares Ethereum Trust ETF",
                market="NASDAQ",
                quantity=120.0,
                cost_basis=24.0,
                current_price=31.0,
                asset_class="crypto_etf",
                instrument_type="crypto_etf",
                issuer_name="iShares",
                issuer_canonical_id="ISHARES",
                underlying_issuer_name="Ethereum",
                underlying_ticker="ETH",
                listing_country="United States",
                country_of_risk="Global",
                region="Global",
                sector="Digital Assets",
                industry="Crypto asset ETF",
                theme=["crypto beta"],
                risk_bucket="crypto_beta",
                base_currency="USD",
                lookthrough_source="Manual fixture, not provider data.",
                lookthrough_components=[
                    LookThroughComponent(
                        component_issuer_name="Ethereum",
                        component_issuer_canonical_id="ETHEREUM",
                        component_ticker="ETH",
                        component_weight=1.0,
                        sector="Digital Assets",
                        industry="Crypto asset",
                        country_of_risk="Global",
                        region="Global",
                        theme=["crypto beta"],
                        instrument_type="crypto",
                        source_note="Manual fixture underlying.",
                    )
                ],
                notes="Crypto beta fixture, not AI equity exposure.",
            ),
            Holding(
                ticker="SMS",
                name="Samsung Electronics GDS-like holding",
                market="LSE",
                quantity=12.0,
                cost_basis=1400.0,
                current_price=1500.0,
                asset_class="gds",
                instrument_type="gds",
                issuer_name="Samsung Electronics",
                issuer_canonical_id="SAMSUNG_ELECTRONICS",
                underlying_issuer_name="Samsung Electronics",
                underlying_ticker="005930.KS",
                listing_country="United Kingdom",
                country_of_risk="South Korea",
                region="Asia",
                sector="Information Technology",
                industry="Semiconductors",
                theme=["HBM", "semiconductor", "AI infrastructure"],
                risk_bucket="semiconductor_cycle",
                base_currency="USD",
                notes="Fake GDS-like fixture for non-US listing coverage.",
            ),
        ],
    )
